import type {Metadata} from "next";
import "./globals.css";
import Header from "@/components/header/Header";
import Footer from "@/components/footer/Footer";

import {ToastContainer} from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';

export const metadata: Metadata = {
    title: "Loonum Enterprise",
    description: "Generated by Loonum Enterprise",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {

    return (
        <html lang="en">
            <body className={'relative hide-scrollbar overflow-x-hidden'}>
                <Header/>
                <ToastContainer />
                    {children}
                <Footer/>
            </body>
        </html>
    );
}
